name: cek_handphone
version: 1.0.0+1
publish_to: none
description: Mencari handphone
environment: 
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dropdown_search: 5.0.6
  http: 1.1.0
  dio: 5.3.2
  faker: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

